### PR TITLE
Weather API & more styling

### PR DESCRIPTION
**Pull request by HnryStGTkr**
sup

### CODE REVIEW

**Comment by HnryStGTkr** [comment]
more files to host somewhere, `npx serve .` on your local, that way your API key isn't public.
stuff for you to update:
there is image files referenced in index.html (cars) and style.css (topography)
add your api key and lat and long to script.js

**Comment by pizza-plz** [comment]
yoooooo pulling this in now

**Comment by pizza-plz** [comment]
thanks for all your work dude seriously

**Comment by HnryStGTkr** [comment]
you're welcome dude
hope it works well for you

**Pull request merged**
